import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://diogopassos.pt">DiogoPassos.pt!</a>
        </h1>

        <p className={styles.description}>
          Page under{' '}
          <code className={styles.code}>Construction</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a href="https://diogopassos.pt"><span>Powered By <b>DiogoPassos.pt</b></span></a>
      </footer>
    </div>
  )
}
